<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DoohClick.DataAccess\DoohClick.DataAccess.csproj" />
    <ProjectReference Include="..\DoohClick.Model\DoohClick.Model.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Application\commercial\campaign\" />
  </ItemGroup>

</Project>
