<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DoohClick.Interface\DoohClick.Interface.csproj" />
    <ProjectReference Include="..\DoohClick.Model\DoohClick.Model.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Application\" />
  </ItemGroup>

</Project>
