<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>d9b87eaf-82b7-4efb-841c-f95d9c303739</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DoohClick.DataAccess\DoohClick.DataAccess.csproj" />
    <ProjectReference Include="..\DoohClick.Interface\DoohClick.Interface.csproj" />
    <ProjectReference Include="..\DoohClick.Model\DoohClick.Model.csproj" />
    <ProjectReference Include="..\DoohClick.Service\DoohClick.Service.csproj" />
  </ItemGroup>

</Project>
